import { InstrumentSoundPreset } from '../types';

export const INSTRUMENT_PRESETS: InstrumentSoundPreset[] = [
  // ==================== PIANOS & KEYS ====================
  {
    id: 'grand_concert_piano',
    name: 'Grand Concert Piano',
    category: 'Pianos & Keys',
    description: 'Rich acoustic grand piano with physical hammer overtones and wooden resonance.',
    icon: 'Piano',
    patch: {
      waveType: 'piano',
      osc2Wave: 'triangle',
      osc2Detune: 4,
      osc2Octave: 1,
      oscMix: 0.25,
      unisonVoices: 2,
      unisonDetune: 3,
      attack: 0.005,
      decay: 1.2,
      sustain: 0.15,
      release: 0.6,
      filterCutoff: 5500,
      resonance: 1.2,
      filterEnvAmount: 40,
      filterAttack: 0.005,
      filterDecay: 0.8,
      volume: 0.85,
    },
    tags: ['Acoustic', 'Natural', 'Solo', 'Melody', 'Ballad'],
  },
  {
    id: 'rhodes_mk1_electric',
    name: '70s Rhodes MK1 Electric',
    category: 'Pianos & Keys',
    description: 'Warm bell-like tine resonance with vintage electric piano character.',
    icon: 'Disc',
    patch: {
      waveType: 'rhodes',
      osc2Wave: 'sine',
      osc2Detune: 7,
      osc2Octave: 0,
      oscMix: 0.4,
      unisonVoices: 2,
      unisonDetune: 5,
      attack: 0.008,
      decay: 1.4,
      sustain: 0.35,
      release: 0.5,
      filterCutoff: 3800,
      resonance: 1.8,
      lfoRate: 3.5,
      lfoDepth: 0.15,
      lfoTarget: 'pan',
      volume: 0.8,
    },
    tags: ['Vintage', 'Soul', 'Lofi', 'Jazz', 'Chill'],
  },
  {
    id: 'dx7_digital_epiano',
    name: '80s DX7 FM Digital Piano',
    category: 'Pianos & Keys',
    description: 'Iconic 1980s crystal FM electric piano with crisp bell attack.',
    icon: 'Sparkles',
    patch: {
      waveType: 'fm',
      osc2Wave: 'sine',
      osc2Detune: 2,
      osc2Octave: 1,
      oscMix: 0.5,
      attack: 0.002,
      decay: 1.0,
      sustain: 0.25,
      release: 0.7,
      filterCutoff: 8000,
      resonance: 2.0,
      volume: 0.75,
    },
    tags: ['80s', 'Pop', 'Synthwave', 'Bright', 'FM'],
  },
  {
    id: 'm1_house_organ',
    name: 'M1 Classic House Organ',
    category: 'Pianos & Keys',
    description: 'Punchy 90s dance club organ stab, staple of classic and deep house.',
    icon: 'Radio',
    patch: {
      waveType: 'organ',
      osc2Wave: 'square',
      osc2Detune: 12,
      osc2Octave: 1,
      oscMix: 0.3,
      attack: 0.003,
      decay: 0.4,
      sustain: 0.5,
      release: 0.15,
      filterCutoff: 4200,
      resonance: 2.2,
      drive: 0.2,
      volume: 0.85,
    },
    tags: ['House', 'Club', '90s', 'Punchy', 'Organ'],
  },
  {
    id: 'cathedral_pipe_organ',
    name: 'Cathedral Pipe Organ',
    category: 'Pianos & Keys',
    description: 'Massive multi-harmonic pipe organ with majestic acoustic presence.',
    icon: 'Layers',
    patch: {
      waveType: 'organ',
      osc2Wave: 'sawtooth',
      osc2Detune: 6,
      osc2Octave: -1,
      oscMix: 0.45,
      unisonVoices: 4,
      unisonDetune: 8,
      attack: 0.05,
      decay: 0.6,
      sustain: 0.85,
      release: 0.8,
      filterCutoff: 6500,
      resonance: 1.5,
      volume: 0.75,
    },
    tags: ['Majestic', 'Church', 'Epic', 'Ambient'],
  },
  {
    id: 'jazz_vibraphone',
    name: 'Jazz Vibraphone & Chimes',
    category: 'Pianos & Keys',
    description: 'Warm metallic bar resonance with motor vibrato tremolo.',
    icon: 'Bell',
    patch: {
      waveType: 'bell',
      osc2Wave: 'sine',
      osc2Detune: 3,
      osc2Octave: 1,
      oscMix: 0.35,
      attack: 0.003,
      decay: 1.6,
      sustain: 0.1,
      release: 0.9,
      filterCutoff: 4500,
      resonance: 2.8,
      lfoRate: 5.0,
      lfoDepth: 0.25,
      lfoTarget: 'volume',
      volume: 0.8,
    },
    tags: ['Jazz', 'Mallet', 'Chill', 'Vibrato'],
  },

  // ==================== SYNTHS & LEADS ====================
  {
    id: 'cyberpunk_supersaw',
    name: 'Cyberpunk 2077 Supersaw',
    category: 'Synths & Leads',
    description: '7-voice hyper-detuned trance & synthwave monster lead with wide stereo field.',
    icon: 'Zap',
    patch: {
      waveType: 'supersaw',
      osc2Wave: 'sawtooth',
      osc2Detune: 16,
      osc2Octave: 0,
      oscMix: 0.5,
      unisonVoices: 7,
      unisonDetune: 24,
      attack: 0.01,
      decay: 0.3,
      sustain: 0.7,
      release: 0.4,
      filterCutoff: 7500,
      resonance: 3.2,
      filterEnvAmount: 50,
      filterAttack: 0.01,
      filterDecay: 0.35,
      drive: 0.3,
      volume: 0.8,
    },
    tags: ['Cyberpunk', 'Trance', 'Massive', 'EDM', 'Anthem'],
  },
  {
    id: 'blade_runner_cs80',
    name: 'Blade Runner CS-80 Synth',
    category: 'Synths & Leads',
    description: 'Iconic cinematic brassy lead with expressive pitch-swell and analog warmth.',
    icon: 'Activity',
    patch: {
      waveType: 'sawtooth',
      osc2Wave: 'sawtooth',
      osc2Detune: 9,
      osc2Octave: 0,
      oscMix: 0.45,
      unisonVoices: 4,
      unisonDetune: 12,
      attack: 0.12,
      decay: 0.5,
      sustain: 0.75,
      release: 0.8,
      filterCutoff: 3200,
      resonance: 2.4,
      lfoRate: 4.2,
      lfoDepth: 0.18,
      lfoTarget: 'filter',
      volume: 0.75,
    },
    tags: ['Cinematic', 'Vangelis', 'Analog', 'Moody', 'Sci-Fi'],
  },
  {
    id: 'acid_303_screamer',
    name: 'Acid 303 Resonance Lead',
    category: 'Synths & Leads',
    description: 'Self-oscillating squelchy resonant Roland TB-303 lead with drive.',
    icon: 'Flame',
    patch: {
      waveType: 'acid_303',
      attack: 0.003,
      decay: 0.2,
      sustain: 0.25,
      release: 0.15,
      filterCutoff: 2200,
      resonance: 8.5,
      filterEnvAmount: 85,
      filterAttack: 0.002,
      filterDecay: 0.18,
      drive: 0.65,
      volume: 0.85,
    },
    tags: ['Acid', 'Techno', '303', 'Squelch', 'Club'],
  },
  {
    id: 'chiptune_8bit_arcade',
    name: '8-Bit Chiptune Arcade Lead',
    category: 'Synths & Leads',
    description: 'Authentic retro GameBoy / NES 25% pulse wave chiptune lead.',
    icon: 'Gamepad2',
    patch: {
      waveType: 'square',
      attack: 0.001,
      decay: 0.1,
      sustain: 0.8,
      release: 0.05,
      filterCutoff: 18000,
      resonance: 1.0,
      drive: 0.1,
      volume: 0.7,
    },
    tags: ['Retro', 'Gaming', '8bit', 'Arcade', 'Chiptune'],
  },
  {
    id: 'eurodance_90s_lead',
    name: 'Eurodance 90s Rave Lead',
    category: 'Synths & Leads',
    description: 'Bright high-energy rave sound with snappy transient punch.',
    icon: 'Sun',
    patch: {
      waveType: 'sawtooth',
      osc2Wave: 'square',
      osc2Detune: 8,
      osc2Octave: 1,
      oscMix: 0.35,
      unisonVoices: 3,
      unisonDetune: 10,
      attack: 0.004,
      decay: 0.25,
      sustain: 0.6,
      release: 0.25,
      filterCutoff: 6000,
      resonance: 2.0,
      drive: 0.25,
      volume: 0.8,
    },
    tags: ['90s', 'Rave', 'Eurodance', 'Happy', 'Anthem'],
  },
  {
    id: 'trance_anthem_pluck',
    name: 'Trance Anthem Fast Pluck',
    category: 'Synths & Leads',
    description: 'Tight exponential envelope synth pluck for rapid 16th-note arpeggiations.',
    icon: 'Zap',
    patch: {
      waveType: 'pluck',
      osc2Wave: 'sawtooth',
      osc2Detune: 6,
      osc2Octave: 1,
      oscMix: 0.3,
      attack: 0.002,
      decay: 0.18,
      sustain: 0.0,
      release: 0.15,
      filterCutoff: 4000,
      resonance: 4.5,
      filterEnvAmount: 70,
      filterAttack: 0.002,
      filterDecay: 0.14,
      volume: 0.85,
    },
    tags: ['Trance', 'Pluck', 'Arp', 'Melodic', 'EDM'],
  },

  // ==================== BASS & 808 ====================
  {
    id: 'trap_808_sub_boom',
    name: 'Trap 808 Sub-Boom',
    category: 'Bass & 808',
    description: 'Earth-shaking saturated 808 sub bass with pitch-dive transient and warm saturation.',
    icon: 'Volume2',
    patch: {
      waveType: 'sub_808',
      attack: 0.002,
      decay: 0.8,
      sustain: 0.45,
      release: 0.4,
      filterCutoff: 800,
      resonance: 1.5,
      drive: 0.45,
      subBassGlide: 0.08,
      volume: 0.95,
    },
    tags: ['Trap', '808', 'Sub', 'HipHop', 'Boom'],
  },
  {
    id: 'moog_model_d_bass',
    name: 'Minimoog Model D Sub',
    category: 'Bass & 808',
    description: 'Legendary 3-oscillator ladder filter warm analog fat bass.',
    icon: 'Radio',
    patch: {
      waveType: 'sawtooth',
      osc2Wave: 'square',
      osc2Detune: -7,
      osc2Octave: -1,
      oscMix: 0.6,
      unisonVoices: 2,
      unisonDetune: 6,
      attack: 0.005,
      decay: 0.35,
      sustain: 0.5,
      release: 0.2,
      filterCutoff: 1200,
      resonance: 4.2,
      filterEnvAmount: 60,
      filterAttack: 0.005,
      filterDecay: 0.25,
      drive: 0.35,
      volume: 0.9,
    },
    tags: ['Analog', 'Moog', 'Warm', 'Deep', 'Fat'],
  },
  {
    id: 'reese_dnb_warp_bass',
    name: 'Reese DnB Warp Bass',
    category: 'Bass & 808',
    description: 'Detuned dual-saw phase-canceling reese bass for Drum & Bass and Dubstep.',
    icon: 'Wind',
    patch: {
      waveType: 'sawtooth',
      osc2Wave: 'sawtooth',
      osc2Detune: 18,
      osc2Octave: 0,
      oscMix: 0.5,
      unisonVoices: 4,
      unisonDetune: 20,
      attack: 0.02,
      decay: 0.6,
      sustain: 0.85,
      release: 0.3,
      filterCutoff: 1800,
      resonance: 3.0,
      lfoRate: 1.5,
      lfoDepth: 0.3,
      lfoTarget: 'filter',
      drive: 0.4,
      volume: 0.85,
    },
    tags: ['DnB', 'Reese', 'Heavy', 'Jungle', 'Wobble'],
  },
  {
    id: 'deep_house_donk_bass',
    name: 'Deep House Donk Bass',
    category: 'Bass & 808',
    description: 'Metallic punchy FM donk bass designed for modern club grooves.',
    icon: 'Zap',
    patch: {
      waveType: 'fm',
      osc2Wave: 'sine',
      osc2Detune: 0,
      osc2Octave: -1,
      oscMix: 0.4,
      attack: 0.002,
      decay: 0.22,
      sustain: 0.1,
      release: 0.1,
      filterCutoff: 2600,
      resonance: 3.5,
      drive: 0.25,
      volume: 0.9,
    },
    tags: ['House', 'Donk', 'FM', 'Punchy', 'Groove'],
  },

  // ==================== VOCAL & VOICES ====================
  {
    id: 'celestial_choir_aahh',
    name: 'Celestial Choir "Aahh"',
    category: 'Vocal & Voices',
    description: 'Harmonic formant-filtered human vocal choir synthesis with lush stereo spread.',
    icon: 'Mic',
    patch: {
      waveType: 'formant_vocal',
      formantVowel: 'a',
      osc2Wave: 'sawtooth',
      osc2Detune: 8,
      osc2Octave: 0,
      oscMix: 0.35,
      unisonVoices: 5,
      unisonDetune: 14,
      attack: 0.08,
      decay: 0.6,
      sustain: 0.85,
      release: 0.7,
      filterCutoff: 4500,
      resonance: 2.0,
      volume: 0.75,
    },
    tags: ['Vocal', 'Choir', 'Human', 'Angelic', 'Aahh'],
  },
  {
    id: 'ethereal_angelic_oohh',
    name: 'Ethereal Angelic "Oohh"',
    category: 'Vocal & Voices',
    description: 'Gentle warm feminine vocal choir pad with rounded resonant formant filtering.',
    icon: 'Sparkles',
    patch: {
      waveType: 'formant_vocal',
      formantVowel: 'o',
      osc2Wave: 'triangle',
      osc2Detune: 5,
      osc2Octave: 0,
      oscMix: 0.4,
      unisonVoices: 4,
      unisonDetune: 10,
      attack: 0.12,
      decay: 0.8,
      sustain: 0.8,
      release: 0.9,
      filterCutoff: 3200,
      resonance: 1.8,
      volume: 0.75,
    },
    tags: ['Vocal', 'Oohh', 'Airy', 'Dreamy', 'Pad'],
  },
  {
    id: 'robot_cyber_vocoder',
    name: 'Robot Cyber Vocoder Voice',
    category: 'Vocal & Voices',
    description: 'Robotic Kraftwerk / Daft Punk vocoder formant voice.',
    icon: 'Cpu',
    patch: {
      waveType: 'formant_vocal',
      formantVowel: 'e',
      osc2Wave: 'square',
      osc2Detune: 0,
      osc2Octave: -1,
      oscMix: 0.5,
      attack: 0.005,
      decay: 0.4,
      sustain: 0.7,
      release: 0.2,
      filterCutoff: 3800,
      resonance: 5.0,
      drive: 0.35,
      volume: 0.8,
    },
    tags: ['Vocoder', 'Robot', 'Cyber', 'Daft', 'Electro'],
  },
  {
    id: 'trap_vocal_chant_chop',
    name: 'Trap Vocal Chant Chop',
    category: 'Vocal & Voices',
    description: 'Snappy pitched vocal stab popular in trap, drill, and hip-hop beats.',
    icon: 'Radio',
    patch: {
      waveType: 'formant_vocal',
      formantVowel: 'u',
      attack: 0.002,
      decay: 0.16,
      sustain: 0.0,
      release: 0.1,
      filterCutoff: 5000,
      resonance: 3.5,
      filterEnvAmount: 50,
      filterAttack: 0.002,
      filterDecay: 0.12,
      drive: 0.3,
      volume: 0.85,
    },
    tags: ['Vocal', 'Chant', 'Trap', 'Stab', 'Chop'],
  },

  // ==================== PADS & ATMOS ====================
  {
    id: 'ambient_shimmer_pad',
    name: 'Ambient Shimmer Pad',
    category: 'Pads & Atmos',
    description: 'Vast cosmic atmosphere with shimmering octave overtones and slow evolution.',
    icon: 'Cloud',
    patch: {
      waveType: 'sawtooth',
      osc2Wave: 'sine',
      osc2Detune: 12,
      osc2Octave: 1,
      oscMix: 0.45,
      unisonVoices: 5,
      unisonDetune: 16,
      attack: 0.25,
      decay: 1.2,
      sustain: 0.9,
      release: 1.5,
      filterCutoff: 3000,
      resonance: 1.8,
      lfoRate: 0.6,
      lfoDepth: 0.25,
      lfoTarget: 'filter',
      volume: 0.7,
    },
    tags: ['Ambient', 'Shimmer', 'Cosmic', 'Atmospheric', 'Lush'],
  },
  {
    id: 'solina_analog_strings',
    name: '80s Solina Analog Strings',
    category: 'Pads & Atmos',
    description: 'Vintage analog string ensemble synthesizer with warm chorus effect.',
    icon: 'Music',
    patch: {
      waveType: 'strings',
      osc2Wave: 'sawtooth',
      osc2Detune: 7,
      osc2Octave: 0,
      oscMix: 0.5,
      unisonVoices: 4,
      unisonDetune: 12,
      attack: 0.1,
      decay: 0.6,
      sustain: 0.85,
      release: 0.7,
      filterCutoff: 4800,
      resonance: 1.4,
      volume: 0.75,
    },
    tags: ['Strings', 'Vintage', '80s', 'Warm', 'Juno'],
  },
  {
    id: 'lofi_vinyl_keys_pad',
    name: 'Lo-Fi Chillhop Vinyl Pad',
    category: 'Pads & Atmos',
    description: 'Wobbly tape pitch flutter with warm filtered cozy presence.',
    icon: 'Disc',
    patch: {
      waveType: 'rhodes',
      osc2Wave: 'triangle',
      osc2Detune: 8,
      osc2Octave: 0,
      oscMix: 0.35,
      attack: 0.04,
      decay: 0.8,
      sustain: 0.6,
      release: 0.6,
      filterCutoff: 2200,
      resonance: 1.5,
      lfoRate: 2.2,
      lfoDepth: 0.12,
      lfoTarget: 'pitch',
      volume: 0.8,
    },
    tags: ['Lofi', 'Chillhop', 'Vinyl', 'Wobbly', 'Cozy'],
  },

  // ==================== BRASS & PLUCKS ====================
  {
    id: 'synth_brass_fanfare',
    name: '80s Synth Brass Fanfare',
    category: 'Brass & Plucks',
    description: 'Punchy Oberheim / Prophet synth brass stabs with dynamic filter opening.',
    icon: 'Radio',
    patch: {
      waveType: 'brass',
      osc2Wave: 'sawtooth',
      osc2Detune: 10,
      osc2Octave: 0,
      oscMix: 0.4,
      unisonVoices: 3,
      unisonDetune: 12,
      attack: 0.03,
      decay: 0.4,
      sustain: 0.55,
      release: 0.3,
      filterCutoff: 2800,
      resonance: 2.5,
      filterEnvAmount: 65,
      filterAttack: 0.04,
      filterDecay: 0.3,
      volume: 0.8,
    },
    tags: ['Brass', '80s', 'Stab', 'Punchy', 'Pop'],
  },
  {
    id: 'african_kalimba_pluck',
    name: 'Plucked African Kalimba',
    category: 'Brass & Plucks',
    description: 'Acoustic thumb piano metal tine plucking with warm wooden resonance.',
    icon: 'Sparkles',
    patch: {
      waveType: 'karplus',
      osc2Wave: 'sine',
      osc2Detune: 0,
      osc2Octave: 1,
      oscMix: 0.25,
      attack: 0.001,
      decay: 0.6,
      sustain: 0.05,
      release: 0.4,
      filterCutoff: 5500,
      resonance: 3.0,
      volume: 0.8,
    },
    tags: ['Kalimba', 'Acoustic', 'Pluck', 'Organic', 'Afro'],
  },
  {
    id: 'chamber_pizzicato',
    name: 'Orchestral Pizzicato Strings',
    category: 'Brass & Plucks',
    description: 'Crisp plucked acoustic violin & cello strings with wooden body response.',
    icon: 'Music',
    patch: {
      waveType: 'pluck',
      attack: 0.002,
      decay: 0.25,
      sustain: 0.0,
      release: 0.2,
      filterCutoff: 6500,
      resonance: 2.5,
      volume: 0.85,
    },
    tags: ['Orchestral', 'Pizzicato', 'Classical', 'Strings', 'Pluck'],
  },

  // ==================== CLUB FX & DROPS ====================
  {
    id: 'white_noise_riser',
    name: 'Club White Noise Riser',
    category: 'Club FX',
    description: 'Sweeping filter noise riser designed for pre-drop tension builds.',
    icon: 'TrendingUp',
    patch: {
      waveType: 'noise',
      attack: 0.4,
      decay: 0.8,
      sustain: 0.9,
      release: 0.5,
      filterCutoff: 800,
      resonance: 6.0,
      filterEnvAmount: 90,
      filterAttack: 0.6,
      filterDecay: 0.2,
      volume: 0.7,
    },
    tags: ['Riser', 'FX', 'Build', 'Drop', 'Club'],
  },
  {
    id: 'laser_zap_sweep',
    name: 'Club Laser Zap FX',
    category: 'Club FX',
    description: 'Retro synth laser beam effect for transitions and fills.',
    icon: 'Zap',
    patch: {
      waveType: 'sawtooth',
      attack: 0.001,
      decay: 0.15,
      sustain: 0.0,
      release: 0.1,
      filterCutoff: 12000,
      resonance: 7.0,
      detune: 50,
      volume: 0.8,
    },
    tags: ['Laser', 'Zap', 'Fill', 'Club', 'FX'],
  },
];
