import { MusicComposition } from '../types';

export const SONG_PRESETS: MusicComposition[] = [
  {
    id: 'cyberpunk_synthwave',
    title: 'Neon Odyssey 2088',
    description: 'High-energy cyberpunk synthwave with galloping arpeggiated bass, analog supersaw leads, and punchy 808 percussion.',
    genre: 'Cyberpunk Synthwave',
    tempo: 128,
    key: 'D',
    scale: 'Natural Minor (Aeolian)',
    stepsCount: 16,
    melodySequence: ['D4', null, 'F4', null, 'A4', 'G4', null, 'F4', 'E4', null, 'D4', 'E4', 'F4', null, 'D4', null],
    bassSequence: ['D2', 'D2', 'D2', 'D2', 'A#1', 'A#1', 'A#1', 'A#1', 'C2', 'C2', 'C2', 'C2', 'G1', 'G1', 'A1', 'A1'],
    chordSequence: ['D4', null, null, null, 'A#3', null, null, null, 'C4', null, null, null, 'G3', null, 'A3', null],
    drumPattern: {
      kick: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
      snare: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      hihat: [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      openHat: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
      perc: [false, false, false, true, false, false, false, true, false, false, false, true, false, true, false, false],
    },
    leadSynthPatch: {
      waveType: 'sawtooth',
      attack: 0.01,
      decay: 0.15,
      sustain: 0.6,
      release: 0.25,
      filterCutoff: 3800,
      resonance: 3.5,
      detune: 18,
      drive: 0.3,
      volume: 0.75,
    },
    bassSynthPatch: {
      waveType: 'sawtooth',
      attack: 0.005,
      decay: 0.12,
      sustain: 0.4,
      release: 0.1,
      filterCutoff: 950,
      resonance: 4.0,
      volume: 0.85,
    },
    chordSynthPatch: {
      waveType: 'sawtooth',
      attack: 0.08,
      decay: 0.4,
      sustain: 0.7,
      release: 0.5,
      filterCutoff: 2200,
      resonance: 1.5,
      volume: 0.5,
    },
    fxSettings: {
      reverbWet: 0.35,
      reverbDecay: 2.5,
      delayTime: 0.23,
      delayFeedback: 0.4,
      delayWet: 0.25,
      drive: 0.3,
      bitDepth: 16,
      masterLowpass: 18000,
      masterHighpass: 30,
    },
    cppDspCode: `// C++ DSP Synthesis Engine for Neon Odyssey 2088
#include <cmath>

class CyberpunkEngine {
    float phaseSaw = 0.0f;
    float phaseBass = 0.0f;
public:
    float process(float sampleRate, float fLead, float fBass, float cutoff) {
        phaseSaw += fLead / sampleRate;
        if (phaseSaw >= 1.0f) phaseSaw -= 1.0f;
        float lead = (2.0f * phaseSaw - 1.0f);
        
        phaseBass += fBass / sampleRate;
        if (phaseBass >= 1.0f) phaseBass -= 1.0f;
        float bass = (2.0f * phaseBass - 1.0f) * 1.5f;
        
        return std::tanh(lead * 0.4f + bass * 0.6f);
    }
};`
  },
  {
    id: 'ethereal_ambient',
    title: 'Ethereal Cosmic Drift',
    description: 'Serene ambient landscape with generative bell chimes, warm swelling chords, and celestial stereo reverb reflections.',
    genre: 'Ambient Meditation',
    tempo: 75,
    key: 'F',
    scale: 'Lydian',
    stepsCount: 16,
    melodySequence: ['C5', null, null, 'G4', null, 'A4', null, null, 'E5', null, 'D5', null, 'C5', null, null, null],
    bassSequence: ['F2', null, null, null, 'D2', null, null, null, 'A#1', null, null, null, 'C2', null, null, null],
    chordSequence: ['F4', null, null, null, 'D4', null, null, null, 'A#3', null, null, null, 'C4', null, null, null],
    drumPattern: {
      kick: [true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
      snare: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      hihat: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
      openHat: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      perc: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
    },
    leadSynthPatch: {
      waveType: 'fm',
      attack: 0.15,
      decay: 0.6,
      sustain: 0.4,
      release: 1.5,
      filterCutoff: 4500,
      resonance: 1.2,
      volume: 0.6,
    },
    bassSynthPatch: {
      waveType: 'sine',
      attack: 0.2,
      decay: 0.8,
      sustain: 0.7,
      release: 1.2,
      filterCutoff: 400,
      resonance: 0.5,
      volume: 0.7,
    },
    chordSynthPatch: {
      waveType: 'triangle',
      attack: 0.4,
      decay: 0.9,
      sustain: 0.8,
      release: 2.0,
      filterCutoff: 1800,
      resonance: 0.8,
      volume: 0.55,
    },
    fxSettings: {
      reverbWet: 0.65,
      reverbDecay: 4.5,
      delayTime: 0.4,
      delayFeedback: 0.55,
      delayWet: 0.4,
      drive: 0.0,
      bitDepth: 16,
      masterLowpass: 15000,
      masterHighpass: 40,
    }
  },
  {
    id: 'chiptune_boss',
    title: '8-Bit Dungeon Boss',
    description: 'Nostalgic retro arcade chiptune featuring authentic pulse wave duty cycles, rapid arpeggios, and crunchy noise percussion.',
    genre: 'Chiptune / 8-Bit',
    tempo: 145,
    key: 'A',
    scale: 'Harmonic Minor',
    stepsCount: 16,
    melodySequence: ['A4', 'C5', 'E5', 'A5', 'G#4', 'B4', 'E5', 'G#5', 'A4', 'C5', 'E5', 'A5', 'F5', 'E5', 'D5', 'B4'],
    bassSequence: ['A2', null, 'A2', null, 'E2', null, 'E2', null, 'F2', null, 'F2', null, 'G#2', null, 'E2', null],
    chordSequence: ['A3', null, null, null, 'E3', null, null, null, 'F3', null, null, null, 'E3', null, null, null],
    drumPattern: {
      kick: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, true, false],
      snare: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, true],
      hihat: [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      openHat: [false, false, true, false, false, false, true, false, false, false, true, false, false, true, false, true],
      perc: [true, false, false, true, false, true, false, false, true, false, false, true, false, false, true, false],
    },
    leadSynthPatch: {
      waveType: 'square',
      attack: 0.002,
      decay: 0.08,
      sustain: 0.5,
      release: 0.08,
      filterCutoff: 8000,
      resonance: 1.0,
      volume: 0.7,
    },
    bassSynthPatch: {
      waveType: 'triangle',
      attack: 0.002,
      decay: 0.1,
      sustain: 0.8,
      release: 0.05,
      filterCutoff: 2000,
      resonance: 1.0,
      volume: 0.85,
    },
    chordSynthPatch: {
      waveType: 'square',
      attack: 0.01,
      decay: 0.1,
      sustain: 0.4,
      release: 0.1,
      filterCutoff: 6000,
      resonance: 1.0,
      volume: 0.5,
    },
    fxSettings: {
      reverbWet: 0.15,
      reverbDecay: 1.0,
      delayTime: 0.15,
      delayFeedback: 0.25,
      delayWet: 0.15,
      drive: 0.2,
      bitDepth: 8,
      masterLowpass: 16000,
      masterHighpass: 50,
    }
  },
  {
    id: 'lofi_chillhop',
    title: 'Midnight Rain Study',
    description: 'Relaxed Lo-Fi chillhop beat with dusty 7th Rhodes chords, laid-back swung drums, and warm tape saturation.',
    genre: 'Lo-Fi Chillhop',
    tempo: 84,
    key: 'C',
    scale: 'Dorian',
    stepsCount: 16,
    melodySequence: ['D4', null, 'F4', null, 'A4', null, 'C5', null, 'B4', null, 'G4', null, 'A4', null, null, null],
    bassSequence: ['D2', null, null, 'D2', null, null, 'G1', null, 'C2', null, null, 'C2', null, 'A1', null, null],
    chordSequence: ['D4', null, null, null, 'G3', null, null, null, 'C4', null, null, null, 'A3', null, null, null],
    drumPattern: {
      kick: [true, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false],
      snare: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      hihat: [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false],
      openHat: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false],
      perc: [false, false, true, false, false, false, false, true, false, false, true, false, false, false, false, true],
    },
    leadSynthPatch: {
      waveType: 'triangle',
      attack: 0.05,
      decay: 0.3,
      sustain: 0.5,
      release: 0.4,
      filterCutoff: 2100,
      resonance: 0.8,
      volume: 0.65,
    },
    bassSynthPatch: {
      waveType: 'sine',
      attack: 0.04,
      decay: 0.25,
      sustain: 0.6,
      release: 0.2,
      filterCutoff: 650,
      resonance: 1.0,
      volume: 0.8,
    },
    chordSynthPatch: {
      waveType: 'fm',
      attack: 0.03,
      decay: 0.5,
      sustain: 0.4,
      release: 0.6,
      filterCutoff: 1900,
      resonance: 0.5,
      volume: 0.6,
    },
    fxSettings: {
      reverbWet: 0.4,
      reverbDecay: 3.0,
      delayTime: 0.35,
      delayFeedback: 0.3,
      delayWet: 0.2,
      drive: 0.15,
      bitDepth: 12,
      masterLowpass: 12000,
      masterHighpass: 60,
    }
  },
  {
    id: 'acid_techno_303',
    title: 'Berlin Warehouse Acid 303',
    description: 'Hypnotic driving underground techno with resonant screaming 303 acid line, sub bass kick, and relentless 4/4 drive.',
    genre: 'Acid Techno',
    tempo: 138,
    key: 'F#',
    scale: 'Phrygian',
    stepsCount: 16,
    melodySequence: ['F#3', 'G3', 'F#3', 'C4', 'F#3', 'G3', 'A#3', 'F#3', 'F#3', 'G3', 'F#3', 'C#4', 'F#3', 'E3', 'D3', 'C3'],
    bassSequence: ['F#1', 'F#1', 'F#1', 'F#1', 'G1', 'G1', 'G1', 'G1', 'F#1', 'F#1', 'F#1', 'F#1', 'D1', 'D1', 'E1', 'E1'],
    chordSequence: ['F#3', null, null, null, 'G3', null, null, null, 'F#3', null, null, null, 'D3', null, 'E3', null],
    drumPattern: {
      kick: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
      snare: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      hihat: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
      openHat: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
      perc: [false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, true],
    },
    leadSynthPatch: {
      waveType: 'sawtooth',
      attack: 0.005,
      decay: 0.14,
      sustain: 0.3,
      release: 0.08,
      filterCutoff: 2900,
      resonance: 6.5,
      drive: 0.5,
      volume: 0.8,
    },
    bassSynthPatch: {
      waveType: 'sawtooth',
      attack: 0.005,
      decay: 0.1,
      sustain: 0.3,
      release: 0.05,
      filterCutoff: 800,
      resonance: 5.0,
      volume: 0.85,
    },
    chordSynthPatch: {
      waveType: 'sawtooth',
      attack: 0.01,
      decay: 0.2,
      sustain: 0.5,
      release: 0.2,
      filterCutoff: 2500,
      resonance: 2.0,
      volume: 0.45,
    },
    fxSettings: {
      reverbWet: 0.25,
      reverbDecay: 1.8,
      delayTime: 0.21,
      delayFeedback: 0.45,
      delayWet: 0.3,
      drive: 0.45,
      bitDepth: 16,
      masterLowpass: 19000,
      masterHighpass: 35,
    }
  }
];
